name: Deploy Laravel to Hpanel

on:
  push:
    branches: [develop]

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy to Hpanel

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            cd /home/u723134020/domains/apis.ahmakbar.site
            git clone https://github.com/ahmakbardev/umkm_api.git
            cd /home/u723134020/domains/apis.ahmakbar.site/umkm_api
            chmod +x ~/bin/composer
            echo "export PATH=$HOME/bin:$PATH" >> ~/.bash_profile
            echo "export PATH=$HOME/bin/node/bin:$PATH" >> ~/.bash_profile
            source ~/.bash_profile
            git add .
            git stash
            git pull origin main
            which node
            node -v
            npm -v
            npm i
            npm install --legacy-peer-deps
            npm run prod
            source ~/.bash_profile
            which composer
            composer --version
            composer install
            composer update
            php artisan key:generate
            php artisan route:clear
            php artisan config:cache
            php artisan storage:link
            php artisan optimize

             # Set permissions for storage directory
            find /home/u723134020/domains/apis.ahmakbar.site/umkm_api/storage -type d -exec chmod 755 {} \;
            find /home/u723134020/domains/apis.ahmakbar.site/umkm_api/storage -type f -exec chmod 644 {} \;

            # rm -rf /home/u723134020/domains/apis.ahmakbar.site/public_html/
            ln -s /home/u723134020/domains/apis.ahmakbar.site/umkm_api/public/* /home/u723134020/domains/apis.ahmakbar.site/public_html/

            
